// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using szakdolgozat;

#nullable disable

namespace szakdolgozat.Migrations
{
    [DbContext(typeof(AssetDbContext))]
    [Migration("20250312131817_AddVulnerabilities")]
    partial class AddVulnerabilities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("szakdolgozat.Models.Asset", b =>
                {
                    b.Property<int>("AssetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetID"));

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AssetTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("PurchaseDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SubtypeID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Value")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AssetID");

                    b.HasIndex("AssetID")
                        .IsUnique();

                    b.HasIndex("AssetTypeID");

                    b.HasIndex("SubtypeID");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("szakdolgozat.Models.AssetAssignment", b =>
                {
                    b.Property<int>("AssignmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentID"));

                    b.Property<int>("AssetID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AssignmentDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AssignmentID");

                    b.HasIndex("AssetID");

                    b.HasIndex("AssignmentID")
                        .IsUnique();

                    b.ToTable("AssetAssignments");
                });

            modelBuilder.Entity("szakdolgozat.Models.AssetLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AssetID")
                        .HasColumnType("int");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Timestamp")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.HasKey("LogID");

                    b.HasIndex("AssetID");

                    b.HasIndex("LogID")
                        .IsUnique();

                    b.ToTable("AssetLogs");
                });

            modelBuilder.Entity("szakdolgozat.Models.AssetType", b =>
                {
                    b.Property<int>("TypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeID"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TypeID");

                    b.HasIndex("TypeID")
                        .IsUnique();

                    b.ToTable("AssetTypes");
                });

            modelBuilder.Entity("szakdolgozat.Models.AssetVulnerability", b =>
                {
                    b.Property<int>("AssetID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("VulnerabilityID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Impact")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Probability")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("AssetID", "VulnerabilityID");

                    b.HasIndex("AssetID");

                    b.HasIndex("VulnerabilityID");

                    b.ToTable("AssetVulnerabilities");
                });

            modelBuilder.Entity("szakdolgozat.Models.Subtype", b =>
                {
                    b.Property<int>("TypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeID"));

                    b.Property<int?>("AssetTypeID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TypeID");

                    b.HasIndex("AssetTypeID");

                    b.HasIndex("TypeID")
                        .IsUnique();

                    b.ToTable("Subtypes");
                });

            modelBuilder.Entity("szakdolgozat.Models.Vulnerability", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.ToTable("Vulnerabilities");
                });

            modelBuilder.Entity("szakdolgozat.Models.Asset", b =>
                {
                    b.HasOne("szakdolgozat.Models.AssetType", "AssetType")
                        .WithMany()
                        .HasForeignKey("AssetTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("szakdolgozat.Models.Subtype", "Subtype")
                        .WithMany()
                        .HasForeignKey("SubtypeID");

                    b.Navigation("AssetType");

                    b.Navigation("Subtype");
                });

            modelBuilder.Entity("szakdolgozat.Models.AssetAssignment", b =>
                {
                    b.HasOne("szakdolgozat.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("szakdolgozat.Models.AssetLog", b =>
                {
                    b.HasOne("szakdolgozat.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("szakdolgozat.Models.AssetVulnerability", b =>
                {
                    b.HasOne("szakdolgozat.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("szakdolgozat.Models.Vulnerability", "Vulnerability")
                        .WithMany()
                        .HasForeignKey("VulnerabilityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Vulnerability");
                });

            modelBuilder.Entity("szakdolgozat.Models.Subtype", b =>
                {
                    b.HasOne("szakdolgozat.Models.AssetType", "AssetType")
                        .WithMany()
                        .HasForeignKey("AssetTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetType");
                });
#pragma warning restore 612, 618
        }
    }
}
